language: node_js
node_js:
  - "stable"
  - "6"
  - "5"
  - "4"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - cp .env.example .env
script:
  - npm run lint 
  - gulp build