# Uncomment this line to define a global platform for your project
platform :osx, '10.10'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FloatBehind' do
    pod 'Sparkle', '~> 1.14.0'
    pod 'SwiftHTTP', '~> 2.0.2'
    pod 'JSONJoy-Swift', '~> 2.0.1'
end

target 'FloatBehindTests' do
    
end

target 'FloatBehindUITests' do
    
end

